/**
 * movie-cache.ts — Type-safe reader for build-time TMDB JSON cache files.
 * Cache files are generated by: node src/scripts/movie-sync.mjs
 * They live in: src/data/cache/{category}.json
 */

export interface CachedItem {
  id: number;
  type: 'movie' | 'tv';
  title: string;
  year: number;
  rating: number;
  posterPath: string | null;
  backdropPath: string | null;
  posterUrl: string;
  backdropUrl: string;
  overview: string;
  genreIds: number[];
  language: string;
}

interface CacheFile {
  fetchedAt: string;
  category: string;
  count: number;
  items: CachedItem[];
}

// Vite/Astro glob import — loads all existing cache JSON files eagerly at build time.
// Returns an empty object if no files exist yet (safe before first sync run).
const _modules = import.meta.glob<CacheFile>('/src/data/cache/*.json', { eager: true });

/**
 * Returns cached items for a category, optionally limited.
 * Returns [] if cache file doesn't exist or sync hasn't been run yet.
 */
export function getCachedItems(category: string, limit?: number): CachedItem[] {
  const key = `/src/data/cache/${category}.json`;
  const mod = _modules[key];
  // Vite wraps JSON in { default: ... } when using eager glob
  const file = (mod as any)?.default ?? mod;
  const items: CachedItem[] = file?.items ?? [];
  return limit ? items.slice(0, limit) : items;
}

/** True if cache file is missing or has no items (sync hasn't been run). */
export function isCacheEmpty(category: string): boolean {
  return getCachedItems(category).length === 0;
}

/** Metadata about when the cache was generated. */
export function getCacheMeta(category: string): { fetchedAt: string; count: number } | null {
  const key = `/src/data/cache/${category}.json`;
  const mod = _modules[key];
  const file = (mod as any)?.default ?? mod;
  if (!file) return null;
  return { fetchedAt: file.fetchedAt ?? '', count: file.count ?? 0 };
}
