/**
 * realTitles.ts — Type-safe reader for the real, TMDB-backed title dataset.
 * Generated by: node src/scripts/movie-sync.mjs -> src/data/cache/titles.json
 * This is the real replacement for the old fictional src/data/sampleTitles.ts.
 */

export interface RealCastMember {
  name: string;
  role: string;
}

export interface RealTitle {
  id: string;
  tmdbId: number;
  slug: string;
  type: 'movie' | 'show';
  title: string;
  year: number;
  rating: number;
  runtime: string;
  posterUrl: string;
  backdropUrl: string;
  overview: string;
  genres: string[];
  languages: string[];
  cast: RealCastMember[];
  director: string;
  trailerUrl: string;
  releaseDate: string;
  status: string;
  seasons?: number;
  episodes?: number;
  relatedIds: string[];
}

interface TitlesFile {
  fetchedAt: string;
  count: number;
  items: RealTitle[];
}

const _modules = import.meta.glob<TitlesFile>('/src/data/cache/titles.json', { eager: true });

function loadAll(): RealTitle[] {
  const mod = _modules['/src/data/cache/titles.json'];
  const file = (mod as any)?.default ?? mod;
  return file?.items ?? [];
}

const ALL_TITLES = loadAll();
const BY_ID = new Map(ALL_TITLES.map(t => [t.id, t]));
const BY_SLUG = new Map(ALL_TITLES.map(t => [t.slug, t]));

export function getAllRealTitles(): RealTitle[] {
  return ALL_TITLES;
}

export function getRealTitlesByType(type: 'movie' | 'show'): RealTitle[] {
  return ALL_TITLES.filter(t => t.type === type);
}

export function getRealTitleBySlug(slug: string): RealTitle | undefined {
  return BY_SLUG.get(slug);
}

/** Related titles resolved from TMDB "similar" results, limited to ones we actually have a page for. */
export function getRelatedRealTitles(title: RealTitle, limit = 6): RealTitle[] {
  const related = title.relatedIds
    .map(id => BY_ID.get(id))
    .filter((t): t is RealTitle => !!t);
  if (related.length >= limit) return related.slice(0, limit);

  // Fall back to same-genre titles if TMDB similar-results don't overlap our set.
  const sameType = ALL_TITLES.filter(t => t.id !== title.id && t.type === title.type);
  const sameGenre = sameType.filter(t => t.genres.some(g => title.genres.includes(g)));
  const seen = new Set(related.map(t => t.id));
  for (const t of sameGenre) {
    if (related.length >= limit) break;
    if (seen.has(t.id)) continue;
    seen.add(t.id);
    related.push(t);
  }
  return related.slice(0, limit);
}
