/**
 * realTitles.ts — Type-safe reader for the real, TMDB-backed title dataset.
 * Generated by: node src/scripts/movie-sync.mjs -> src/data/cache/titles.json
 * This is the real replacement for the old fictional src/data/sampleTitles.ts.
 */
import { isDmcaDenied } from './dmcaDenyList';

export interface RealCastMember {
  name: string;
  role: string;
  /** Build-time synced TMDB profile image URL — avoids runtime API calls per cast card. */
  profileUrl?: string;
}

export interface RealWatchProvider {
  name: string;
  logo: string;
}

/** Official availability from TMDB, resolved to a single region at sync time. */
export interface RealWatchAvailability {
  /** ISO country code the lists below describe — 'IN' unless only US data existed. */
  region: string;
  /** TMDB's own watch page for the title; the providers carry no direct deep links. */
  link: string;
  stream: RealWatchProvider[];
  free: RealWatchProvider[];
  rent: RealWatchProvider[];
  buy: RealWatchProvider[];
}

export interface RealSeason {
  number: number;
  name: string;
  episodes: number;
  /** ISO date, or '' when TMDB has no air date yet. */
  airDate: string;
  posterUrl: string;
  overview: string;
}

/** Ratings from OMDb. Every field is a display string and may be empty. */
export interface RealRatings {
  /** IMDb score out of 10, e.g. "7.6". */
  imdb: string;
  /** Formatted vote count, e.g. "828,114". */
  imdbVotes: string;
  /** Tomatometer, e.g. "85%". */
  rottenTomatoes: string;
  /** Metascore out of 100, e.g. "67". */
  metacritic: string;
  /** Content certificate, e.g. "PG-13". */
  rated: string;
}

export interface RealTitle {
  id: string;
  tmdbId: number;
  slug: string;
  type: 'movie' | 'show';
  title: string;
  year: number;
  rating: number;
  voteCount?: number;
  runtime: string;
  posterUrl: string;
  backdropUrl: string;
  overview: string;
  genres: string[];
  languages: string[];
  /** TMDB `original_language` ISO code — the language the title was made in. */
  originalLanguage?: string;
  /** TMDB production countries. */
  countries?: string[];
  cast: RealCastMember[];
  director: string;
  trailerUrl: string;
  releaseDate: string;
  status: string;
  seasons?: number;
  /**
   * Date the title left the live catalogue. It keeps its English page (so an
   * indexed URL does not turn into a 404) but gets no localized copies.
   */
  retainedSince?: string;
  episodes?: number;
  relatedIds: string[];
  /** null when TMDB lists no official availability in any covered region. */
  watch?: RealWatchAvailability | null;
  /** Numbered seasons only; TMDB's season 0 specials bucket is excluded. */
  seasonList?: RealSeason[];
  imdbId?: string;
  /** Synopses TMDB holds in this site's other locales, keyed by language code. */
  overviews?: Record<string, string>;
  /** Absent when OMDb has no key configured, no listing, or hit its quota. */
  ratings?: RealRatings;
}

interface TitlesFile {
  fetchedAt: string;
  count: number;
  items: RealTitle[];
}

const _modules = import.meta.glob<TitlesFile>('/src/data/cache/titles.json', { eager: true });

function loadAll(): RealTitle[] {
  const mod = _modules['/src/data/cache/titles.json'];
  const file = (mod as any)?.default ?? mod;
  return file?.items ?? [];
}

// DMCA-denied titles never get a page (see the title routes), so they must
// not be linked either: related-title and person grids linked two of them
// from ~80 pages, each link a 404. Filtering here removes them everywhere.
const ALL_TITLES = loadAll().filter(t => !isDmcaDenied(t.slug, t.tmdbId));
const BY_ID = new Map(ALL_TITLES.map(t => [t.id, t]));
const BY_SLUG = new Map(ALL_TITLES.map(t => [t.slug, t]));

export function getAllRealTitles(): RealTitle[] {
  return ALL_TITLES;
}

export function getRealTitlesByType(type: 'movie' | 'show'): RealTitle[] {
  return ALL_TITLES.filter(t => t.type === type);
}

export function getRealTitleBySlug(slug: string): RealTitle | undefined {
  return BY_SLUG.get(slug);
}

/** Related titles resolved from TMDB "similar" results, limited to ones we actually have a page for. */
/**
 * 12 rather than 6: related titles are the main path between title pages, and
 * Search Console showed 9 of 10 sampled title pages still unknown to Google.
 */
export function getRelatedRealTitles(title: RealTitle, limit = 12): RealTitle[] {
  const related = title.relatedIds
    .map(id => BY_ID.get(id))
    .filter((t): t is RealTitle => !!t);
  if (related.length >= limit) return related.slice(0, limit);

  // Fall back to same-genre titles if TMDB similar-results don't overlap our set.
  // Each page starts at its own point in the genre list (stable per title).
  // Starting everyone at the top meant every page linked the same few popular
  // titles and the rest of the catalogue got no internal links at all.
  const sameType = ALL_TITLES.filter(t => t.id !== title.id && t.type === title.type);
  const sameGenre = sameType.filter(t => t.genres.some(g => title.genres.includes(g)));
  const offset = sameGenre.length
    ? [...String(title.id)].reduce((h, ch) => (h * 31 + ch.charCodeAt(0)) >>> 0, 7) % sameGenre.length
    : 0;
  const rotated = [...sameGenre.slice(offset), ...sameGenre.slice(0, offset)];
  const seen = new Set(related.map(t => t.id));
  for (const t of rotated) {
    if (related.length >= limit) break;
    if (seen.has(t.id)) continue;
    seen.add(t.id);
    related.push(t);
  }
  return related.slice(0, limit);
}
