/**
 * scripts/_build_hardcoded_sponsors.mjs
 * ═══════════════════════════════════════════════════════
 * Generates functions/api/sponsors.js, sponsors2.js & link-health.js with inline Base64.
 *
 * ⚠️  DATA SOURCE: src/data/sponsor-links.json (canonical)
 *     Hardcoded lists removed — canonical JSON se read hota hai.
 *
 * Run: node scripts/_build_hardcoded_sponsors.mjs
 * OR:  npm run sponsors:rebuild
 *
 * Note: npm run sponsors:push already does this + KV update.
 * Use this only when you want to rebuild functions/ WITHOUT KV push.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';
import sharp from 'sharp';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

// ── Load canonical manifest ────────────────────────────────────────────────
const MANIFEST_PATH = join(ROOT, 'src', 'data', 'sponsor-links.json');

if (!existsSync(MANIFEST_PATH)) {
  console.error('❌ FATAL: src/data/sponsor-links.json not found!');
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'));
const TRAIL1 = manifest.trail1.filter(s => s.enabled !== false);
const TRAIL2 = manifest.trail2.filter(s => s.enabled !== false);

const manifestHash = createHash('sha256')
  .update(JSON.stringify({ trail1: manifest.trail1, trail2: manifest.trail2 }))
  .digest('hex')
  .substring(0, 16);

// ── Inline Base64 images ───────────────────────────────────────────────────
async function inlineBase64(sponsors) {
  return Promise.all(sponsors.map(async (s) => {
    const imageFile = s.imageFile || s.image.split('/').pop();
    const fp = join(ROOT, 'public', 'links', imageFile);
    let imageData = '';
    if (existsSync(fp)) {
      const buf = await sharp(fp)
        .resize(192, 192, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
        .webp({ quality: 80, effort: 6 })
        .toBuffer();
      imageData = `data:image/webp;base64,${buf.toString('base64')}`;
      console.log(`  ✅ ${s.id} (${buf.length}b)`);
    } else {
      console.warn(`  ⚠️  MISSING image: ${imageFile}`);
    }
    return { name: s.id, label: s.label, tagline: s.tagline, url: s.url, image: s.image, imageData, badge: s.badge };
  }));
}

function toJsArray(sponsors) {
  return sponsors.map(s => {
    const parts = [
      `name: ${JSON.stringify(s.name)}`,
      `label: ${JSON.stringify(s.label)}`,
      `tagline: ${JSON.stringify(s.tagline)}`,
      `url: ${JSON.stringify(s.url)}`,
      `image: ${JSON.stringify(s.image)}`,
      s.imageData ? `imageData: ${JSON.stringify(s.imageData)}` : null,
      `badge: ${JSON.stringify(s.badge)}`,
    ].filter(Boolean);
    return `    { ${parts.join(', ')} }`;
  }).join(',\n');
}

async function main() {
  console.log('\n⚡ Building hardcoded sponsors with inline Base64...');
  console.log(`📋 Source: src/data/sponsor-links.json`);
  console.log(`📋 Version: ${manifest.manifestVersion} | Hash: ${manifestHash}`);
  console.log('Trail 1:');
  const t1 = await inlineBase64(TRAIL1);
  console.log('Trail 2:');
  const t2 = await inlineBase64(TRAIL2);

  const now = new Date().toISOString();

  // 1. functions/api/sponsors.js
  const sponsorsJs = `/**
 * functions/api/sponsors.js — AUTO-GENERATED
 * Source: src/data/sponsor-links.json (canonical)
 * Generated by: scripts/_build_hardcoded_sponsors.mjs
 * Manifest Version: ${manifest.manifestVersion}
 * Manifest Hash: ${manifestHash}
 * Last updated: ${now}
 * DO NOT EDIT MANUALLY
 */

const MANIFEST_VERSION = '${manifest.manifestVersion}';
const MANIFEST_HASH = '${manifestHash}';
const EXPECTED_TRAIL1 = ${manifest.expectedCounts.trail1};
const EXPECTED_TRAIL2 = ${manifest.expectedCounts.trail2};

export async function onRequest(context) {
  const { env } = context;
  const url = new URL(context.request.url);

  try {
    const isRail2 = url.searchParams.get('rail') === '2';
    const key = isRail2 ? 'links2' : 'links';
    const raw = await env.SPONSORS.get(key, { type: 'json' });

    const minExpected = isRail2 ? EXPECTED_TRAIL2 : EXPECTED_TRAIL1;
    const isKvValid = Array.isArray(raw) && raw.length >= minExpected;
    const sponsors = isKvValid
      ? raw
      : (isRail2 ? getDefaultSponsors2() : getDefaultSponsors());

    const kvSource = isKvValid ? 'kv' : 'fallback-safe';

    return new Response(JSON.stringify(sponsors), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'public, max-age=30, s-maxage=30',
        'Access-Control-Allow-Origin': '*',
        'X-Link-Count': String(sponsors.length),
        'X-Link-Source': kvSource,
        'X-Manifest-Version': MANIFEST_VERSION,
        'X-Manifest-Hash': MANIFEST_HASH,
      },
    });
  } catch (err) {
    const isRail2 = url.searchParams.get('rail') === '2';
    return new Response(JSON.stringify(isRail2 ? getDefaultSponsors2() : getDefaultSponsors()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*',
        'X-Link-Source': 'fallback-error',
        'X-Manifest-Version': MANIFEST_VERSION,
      },
    });
  }
}

function getDefaultSponsors() {
  return [
${toJsArray(t1)}
  ];
}

function getDefaultSponsors2() {
  return [
${toJsArray(t2)}
  ];
}
`;

  // 2. functions/api/sponsors2.js
  const sponsors2Js = `/**
 * functions/api/sponsors2.js — AUTO-GENERATED
 * Source: src/data/sponsor-links.json (canonical)
 * Generated by: scripts/_build_hardcoded_sponsors.mjs
 * Manifest Version: ${manifest.manifestVersion}
 * Last updated: ${now}
 */

const EXPECTED_TRAIL2 = ${manifest.expectedCounts.trail2};

export async function onRequest(context) {
  const { env } = context;
  try {
    const raw = await env.SPONSORS.get('links2', { type: 'json' });
    const isKvValid = Array.isArray(raw) && raw.length >= EXPECTED_TRAIL2;
    const sponsors = isKvValid ? raw : getDefaultSponsors2();
    const source = isKvValid ? 'kv' : 'fallback-safe';
    return new Response(JSON.stringify(sponsors), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'public, max-age=30, s-maxage=30',
        'Access-Control-Allow-Origin': '*',
        'X-Link-Count': String(sponsors.length),
        'X-Link-Source': source,
        'X-Manifest-Version': '${manifest.manifestVersion}',
      },
    });
  } catch (err) {
    return new Response(JSON.stringify(getDefaultSponsors2()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'no-cache',
        'Access-Control-Allow-Origin': '*',
        'X-Link-Source': 'fallback-error',
      },
    });
  }
}

function getDefaultSponsors2() {
  return [
${toJsArray(t2)}
  ];
}
`;

  // 3. functions/api/link-health.js
  const linkHealthJs = `/**
 * functions/api/link-health.js — AUTO-GENERATED
 * Source: src/data/sponsor-links.json (canonical)
 * Generated by: scripts/_build_hardcoded_sponsors.mjs
 * Manifest Version: ${manifest.manifestVersion}
 * Manifest Hash: ${manifestHash}
 * Last updated: ${now}
 */

const MANIFEST_VERSION = '${manifest.manifestVersion}';
const MANIFEST_HASH = '${manifestHash}';
const EXPECTED_TRAIL1 = ${manifest.expectedCounts.trail1};
const EXPECTED_TRAIL2 = ${manifest.expectedCounts.trail2};
const REQUIRED_TRAIL1_IDS = ['12th-class-result-check', 'y999-game', 'xd777-sting', 'xd777-gamzu', 'jb-game', 'bet-rupees'];
const REQUIRED_TRAIL2_IDS = ['12th-class-result', 'pkr365', 'm666', 'win786'];

export async function onRequest(context) {
  const { request, env } = context;
  const url = new URL(request.url);

  if (request.method === 'OPTIONS') {
    return new Response(null, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
      },
    });
  }

  let t1Data = null;
  let t2Data = null;
  let source = 'kv';
  let missingCritical = [];

  try {
    if (env.SPONSORS) {
      t1Data = await env.SPONSORS.get('links', { type: 'json' });
      t2Data = await env.SPONSORS.get('links2', { type: 'json' });
    }
  } catch (err) {
    source = 'fallback-error';
  }

  const isT1KvValid = Array.isArray(t1Data) && t1Data.length >= EXPECTED_TRAIL1;
  const isT2KvValid = Array.isArray(t2Data) && t2Data.length >= EXPECTED_TRAIL2;

  const t1Count = Array.isArray(t1Data) ? t1Data.length : 0;
  const t2Count = Array.isArray(t2Data) ? t2Data.length : 0;

  if (!isT1KvValid || !isT2KvValid) {
    source = 'fallback';
  }

  if (Array.isArray(t1Data)) {
    const liveIds1 = t1Data.map(s => s.name || s.id);
    REQUIRED_TRAIL1_IDS.forEach(id => {
      if (!liveIds1.includes(id)) missingCritical.push(\`trail1:\${id}\`);
    });
  } else {
    missingCritical.push('trail1:all_kv_missing');
  }

  if (Array.isArray(t2Data)) {
    const liveIds2 = t2Data.map(s => s.name || s.id);
    REQUIRED_TRAIL2_IDS.forEach(id => {
      if (!liveIds2.includes(id)) missingCritical.push(\`trail2:\${id}\`);
    });
  } else {
    missingCritical.push('trail2:all_kv_missing');
  }

  const isHealthy = isT1KvValid && isT2KvValid && missingCritical.length === 0;

  let healed = false;
  const shouldHeal = (request.method === 'POST' || url.searchParams.get('heal') === '1' || url.searchParams.get('recover') === '1');
  if (shouldHeal && env.SPONSORS && env.SPONSORS.put) {
    try {
      const res1 = await fetch(new URL('/api/sponsors', request.url));
      const res2 = await fetch(new URL('/api/sponsors2', request.url));
      if (res1.ok && res2.ok) {
        const fresh1 = await res1.json();
        const fresh2 = await res2.json();
        if (Array.isArray(fresh1) && fresh1.length >= EXPECTED_TRAIL1) {
          await env.SPONSORS.put('links', JSON.stringify(fresh1));
        }
        if (Array.isArray(fresh2) && fresh2.length >= EXPECTED_TRAIL2) {
          await env.SPONSORS.put('links2', JSON.stringify(fresh2));
        }
        healed = true;
      }
    } catch (_) {}
  }

  const responsePayload = {
    status: isHealthy ? 'healthy' : 'degraded',
    manifestVersion: MANIFEST_VERSION,
    manifestHash: MANIFEST_HASH,
    expectedCounts: {
      trail1: EXPECTED_TRAIL1,
      trail2: EXPECTED_TRAIL2,
      total: EXPECTED_TRAIL1 + EXPECTED_TRAIL2,
    },
    activeCounts: {
      trail1: t1Count,
      trail2: t2Count,
      total: t1Count + t2Count,
    },
    trail1Healthy: isT1KvValid,
    trail2Healthy: isT2KvValid,
    source,
    missingCritical,
    healed,
    checkedAt: new Date().toISOString(),
  };

  return new Response(JSON.stringify(responsePayload, null, 2), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Access-Control-Allow-Origin': '*',
      'X-Link-Status': isHealthy ? 'healthy' : 'degraded',
    },
  });
}
`;

  writeFileSync(join(ROOT, 'functions', 'api', 'sponsors.js'), sponsorsJs, 'utf8');
  writeFileSync(join(ROOT, 'functions', 'api', 'sponsors2.js'), sponsors2Js, 'utf8');
  writeFileSync(join(ROOT, 'functions', 'api', 'link-health.js'), linkHealthJs, 'utf8');
  console.log(`\n✅ Generated functions/api/sponsors.js, sponsors2.js & link-health.js`);
  console.log(`   Trail 1: ${t1.length} sponsors | Trail 2: ${t2.length} sponsors`);
  console.log('   All images hardcoded as inline Base64 ✅\n');
}

main().catch(e => { console.error(e); process.exit(1); });
